# Generated by Django 5.0.1 on 2024-01-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logs_message',
        ),
    ]
