# Generated by Django 5.0.1 on 2024-01-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_delete_logs_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='post',
            field=models.CharField(default='поставщик', max_length=150, verbose_name='пост'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.client', verbose_name='клиент'),
        ),
    ]
