# Generated by Django 4.2 on 2024-02-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_client_owner_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
