# Generated by Django 5.0.1 on 2024-01-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='email',
            field=models.EmailField(default='test@mail.com', max_length=254, verbose_name='почта'),
        ),
    ]
