# Generated by Django 5.0.1 on 2024-01-18 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_email'),
        ('message', '0002_delete_logs_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.client', verbose_name='почта'),
        ),
    ]
