# Generated by Django 5.0.1 on 2024-01-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_email'),
        ('message', '0002_delete_logs_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='email',
        ),
        migrations.AddField(
            model_name='mailing',
            name='email',
            field=models.ManyToManyField(to='message.client', verbose_name='почта'),
        ),
    ]
