# Generated by Django 5.0.1 on 2024-01-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_mailing_email_mailing_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='name',
        ),
    ]
