# Generated by Django 5.0.1 on 2024-01-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_mailing_name'),
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(to='recipients.recipients', verbose_name='адрес'),
        ),
    ]
