# Generated by Django 5.0.1 on 2024-02-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_mailing_recipients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='email',
        ),
        migrations.AddField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('SC', 'Successful'), ('FD', 'Failed')], default='PD', max_length=2, verbose_name='статус'),
        ),
    ]
