# Generated by Django 5.0.1 on 2024-02-08 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_remove_mailing_email_mailing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='send_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 0, 50), verbose_name='время рассылки'),
            preserve_default=False,
        ),
    ]
